services:
    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "SuperPartia1234"
            ACCEPT_EULA: "Y"

